name: app
description: An beautiful sudoku application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.1

environment:
  sdk: ">=2.16.0-154.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  cupertino_icons: ^1.0.2
  utils: ^3.0.3
  collection:
  value_notifier: 0.0.2-prerelease.20
  hive:
  synchronized:
  material_widgets: 0.4.0-preview.7
  path_provider:
  sudoku_core:
    path: ../sudoku/sudoku_core
  adt_annotation: ^3.0.1
  flutter_colorpicker:
  google_fonts:

dev_dependencies:
  adt_generator: ^3.0.0
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # package:intl
  generate: true
