name: sudoku_core
description: A library with the core utilities for the Sudoku Flutter app.
# version: 1.0.0
homepage: https://www.github.com/kalildev/sudoku

environment:
  sdk: '>=2.9.0-5.0 <2.9.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
