name: sudoku_presentation
description: A library with the BLoCs and Repositories for the Sudoku Flutter app.
# version: 1.0.0
homepage: https://www.github.com/kalildev/sudoku

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  sudoku_core:
    path: ../sudoku_core
  bloc: 4.0.0
  meta:

dev_dependencies:
  extra_pedantic: 1.2.0
  test: ^1.6.0
